spring:
  application:
    name: toy
  jmx:
    enabled: true
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

info:
  app:
    encoding: "UTF-8"
    java:
      source: "11"
      target: "11"

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}